/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/40k-milestone-thank-you-598dd1dd669344f2a29e8a912846e9cf
Title: 40k Milestone Thank You :)
*/

import { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { Group } from 'three';
import { GLTF } from 'three-stdlib';
import { Mesh, MeshStandardMaterial } from 'three/src/Three.js';

type GLTFResult = GLTF & {
    nodes: {
        mesh_0: Mesh;
    };
    materials: {
        'Material.002': MeshStandardMaterial;
    };
};

type ModelProps = JSX.IntrinsicElements['group'];

export function BoxModel({ userState, ...props }: ModelProps & { userState?: string }) {
    const group = useRef<Group>(null);
    const { nodes, materials, animations } = useGLTF('/40k_milestone_thank_you.glb') as GLTFResult;
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        if (!actions) {
            // Handle case where actions might be null or undefined
            return;
        }
        console.log(userState);
        console.log("this is action ", actions);
        actions.MorphBake?.reset().fadeIn(0.5).play();
        return () => { actions.MorphBake?.fadeOut(0.5) };
        // if (userState === 'idle') {
        //     actions.Female_Idle?.reset().fadeIn(0.5).play();
        //     return () => { actions.Female_Idle?.fadeOut(0.5) };
        // }
        // if (userState === 'talk') {
        //     actions.Female_Talk?.reset().fadeIn(0.5).play();
        //     return () => { actions.Female_Talk?.fadeOut(0.5) };
        // } else {
        //     actions.Female_Idle?.reset().fadeIn(0.5).play();
        //     return () => { actions.Female_Idle?.fadeOut(0.5) };
        // }
    }, [userState]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.628}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Cube004_0" position={[0, -0.036, 0]}>
                                <mesh
                                    name="mesh_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.mesh_0.geometry}
                                    material={materials['Material.002']}
                                    morphTargetDictionary={nodes.mesh_0.morphTargetDictionary}
                                    morphTargetInfluences={nodes.mesh_0.morphTargetInfluences}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/40k_milestone_thank_you.glb');